### PR TITLE
Added positive_active_energy and negative_active_energy from Power Sensor

### PR DESCRIPTION
**Pull request by andiwirz**

### CODE REVIEW

**Comment by reyntjensw** [comment]
@andiwirz did you check if the code is working?
When running this code I'm getting this error 
`[err] 2022-12-26 08:43:21 [ManagerDrivers] [Driver:luna] [Device:e899ea43-bde3-4243-be01-0a9dbfa2685f] Unavailable (Error: meter_power InvalidTypeError: undefined is undefined but expected number (invalid_type))`

**Comment by andiwirz** [comment]
How can I test the settings without using a version directly from the Homey app store?

**Comment by reyntjensw** [comment]
If you pull the code, execute `homey login`,after that execute `homey app run` and you will be able to test it in your homey

**Comment by andiwirz** [comment]
it works :-)

image

**Comment by reyntjensw** [comment]
@andiwirz since this is not working with everyone there are 2 options to implement this:
- or you implement a checkbox which is set to default off the settings page
- or you check if the value exists and change the code so it doesn't crash when people don't have a power meter

**Comment by andiwirz** [comment]
One question: As you have a Power Meter you see the Import/Export values but you do not have these values?

**Comment by reyntjensw** [comment]
This is the output I get from the `devRealKpiInverter` variable 
`{
  pv2_u: 157.4,
  pv4_u: 0,
  pv22_i: 0,
  power_factor: 1,
  pv6_u: 0,
  pv24_i: 0,
  mppt_total_cap: 11854.71,
  pv8_u: 0,
  open_time: 1672043518000,
  pv22_u: 0,
  a_i: 0.458,
  pv24_u: 0,
  mppt_9_cap: 0,
  c_i: 0.494,
  pv20_u: 0,
  pv19_u: 0,
  pv15_u: 0,
  a_u: 234.5,
  reactive_power: -0.002,
  pv17_u: 0,
  c_u: 239.3,
  mppt_8_cap: 0,
  pv20_i: 0,
  pv15_i: 0,
  pv17_i: 0,
  efficiency: 100,
  pv11_i: 0,
  pv13_i: 0,
  pv11_u: 0,
  mppt_power: 0.3,
  pv13_u: 0,
  run_state: 1,
  close_time: 'N/A',
  pv19_i: 0,
  mppt_7_cap: 0,
  mppt_5_cap: 0,
  pv2_i: 1.18,
  pv4_i: 0,
  active_power: 0.303,
  pv6_i: 0,
  pv8_i: 0,
  mppt_6_cap: 0,
  pv1_u: 481.9,
  pv3_u: 0,
  pv23_i: 0,
  pv5_u: 0,
  pv7_u: 0,
  pv23_u: 0,
  inverter_state: 512,
  pv9_u: 0,
  total_cap: 10108.69,
  mppt_3_cap: 0,
  b_i: 0.479,
  pv21_u: 0,
  mppt_10_cap: 0,
  pv16_u: 0,
  pv18_u: 0,
  temperature: 35.7,
  bc_u: 408.6,
  b_u: 232.5,
  pv21_i: 0,
  elec_freq: 50.02,
  mppt_4_cap: 0,
  pv16_i: 0,
  pv18_i: 0,
  day_cap: 0.79,
  pv12_i: 0,
  pv14_i: 0,
  pv12_u: 0,
  mppt_1_cap: 5573.64,
  pv14_u: 0,
  pv10_u: 0,
  pv1_i: 0.4,
  pv3_i: 0,
  mppt_2_cap: 6281.07,
  pv5_i: 0,
  ab_u: 405.9,
  ca_u: 408.6,
  pv7_i: 0,
  pv10_i: 0,
  pv9_i: 0
}`

**Comment by andiwirz** [comment]
Please check the other variable_ `devRealKpiPowerSensor`

**Comment by reyntjensw** [comment]
this is the output of the `devRealKpiPowerSensor` variable

`{
  meter_status: 1,
  active_cap: 3276.43,
  meter_i: -2.25,
  reverse_active_cap: 5121.89,
  reactive_power: 681,
  power_factor: -0.507,
  active_power: -578,
  run_state: 1,
  meter_u: 228.3,
  grid_frequency: 49.99
}`

**Comment by andiwirz** [comment]
strange - in this case this should work for you as well as you have both values: `reverse_active_cap: 5121.89, reactive_power: 681`

**Comment by reyntjensw** [comment]
it seems to work indeed, I was working on an old branch apparently

**Review by reyntjensw — APPROVED** [review]

**Comment by reyntjensw** [comment]
Can you close all the other branches / MR that are not needed anymore?

**Pull request merged**
